eureka:
  client:
    serviceUrl:
      defaultZone: http://EurekaServer1:8761/eureka,
        http://EurekaServer2:8762/eureka
spring:
  application:
    name: BookQueryService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: librarydb
